/// All supported timezones can be found [here](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations).
/// The list is up to date as of 2024-10-20;
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum TimeZone {
    AcreTime,
    AfghanistanTime,
    AlaskanDaylightTime,
    AlaskanStandardTime,
    AlmaAtaTime,
    AmazonSummerTime,
    AmazonTime,
    AnadyrTime,
    AqtobeTime,
    ArabiaStandardTime,
    ArgentinaTime,
    ArmeniaTime,
    AtlanticDaylightTime,
    AtlanticStandardTime,
    AustralianCentralDaylightSavingTime,
    AustralianCentralStandardTime,
    AustralianEasternDaylightSavingTime,
    AustralianEasternStandardTime,
    AustralianWesternStandardTime,
    AzerbaijanTime,
    AzoresStandardTime,
    AzoresSummerTime,
    BakerIslandTime,
    BangaladeshStandardTime,
    BhutanTime,
    BoliviaTime,
    BougainvilleStandardTime,
    BrasiliaSummerTime,
    BrasiliaTime,
    BritishIndianOceanTime,
    BritishSummerTime,
    BruneiTime,
    CapeVerdeTime,
    CentralAfricaTime,
    CentralDaylightTime,
    CentralEuropeanSummerTime,
    CentralEuropeanTime,
    CentralIndonesianTime,
    CentralStandardTime,
    ChamorroStandardTime,
    ChathamDaylightTime,
    ChathamStandardTime,
    ChileStandardTime,
    ChileSummerTime,
    ChinaStandardTime,
    ChoibalsanStandardTime,
    ChoibalsanSummerTime,
    ChristmasIslandTime,
    ChuukTime,
    ClippertonIslandStandardTime,
    CocosIslandsTime,
    ColombiaSummerTime,
    ColombiaTime,
    CookIslandTime,
    CoordinatedUniversalTime,
    CubaDaylightTime,
    CubaStandardTime,
    DavisTime,
    DumontDUrvilleTime,
    EastAfricaTime,
    EasterIslandStandardTime,
    EasterIslandSummerTime,
    EasternCaribbeanTime,
    EasternDaylightTime,
    EasternEuropeanSummerTime,
    EasternEuropeanTime,
    EasternGreenlandSummerTime,
    EasternGreenlandTime,
    EasternIndonesianTime,
    EasternStandardTime,
    EcuadorTime,
    FalklandIslandsSummerTime,
    FalklandIslandsTime,
    FernandoDeNoronhaTime,
    FijiTime,
    FrenchGuianaTime,
    FrenchSouthernAndAntarcticTime,
    FurtherEasternEuropeanTime,
    GalapagosTime,
    GambierIslandsTime,
    GambierIslandTime,
    GeorgiaStandardTime,
    GilbertIslandTime,
    GreenwichMeanTime,
    GulfStandardTime,
    GuyanaTime,
    HawaiiAleutianDaylightTime,
    HawaiiAleutianStandardTime,
    HeardAndMcDonaldIslandsTime,
    HeureAvanceeDEuropeCentrale,
    HongKongTime,
    HovdTime,
    IndianOceanTime,
    IndianStandardTime,
    IndochinaTime,
    InternationalDateLineWestTime,
    IranDaylightTime,
    IranStandardTime,
    IrishStandardTime,
    IrkutskTime,
    IsraelDaylightTime,
    IsraelStandardTime,
    JapanStandardTime,
    KaliningradTime,
    KamchatkaTime,
    KoreaStandardTime,
    KosraeTime,
    KrasnoyarskTime,
    KyrgyzstanTime,
    LineIslandsTime,
    LordHoweStandardTime,
    LordHoweSummerTime,
    MacquarieIslandStationTime,
    MagadanTime,
    MalaysiaStandardTime,
    MalaysiaTime,
    MaldivesTime,
    MarquesasIslandsTime,
    MarshallIslandsTime,
    MauritiusTime,
    MawsonStationTime,
    MiddleEuropeanSummerTime,
    MiddleEuropeanTime,
    MoscowTime,
    MountainDaylightTime,
    MountainStandardTime,
    MyanmarStandardTime,
    NepalTime,
    NewCaledoniaTime,
    NewfoundlandDaylightTime,
    NewfoundlandStandardTime,
    NewfoundlandTime,
    NewZealandDaylightTime,
    NewZealandStandardTime,
    NiueTime,
    NorfolkIslandTime,
    NovosibirskTime,
    OmskTime,
    OralTime,
    PacificDaylightTime,
    PacificStandardTime,
    PakistanStandardTime,
    PalauTime,
    PapuaNewGuineaTime,
    ParaguaySummerTime,
    ParaguayTime,
    PeruTime,
    PhilipineStandardTime,
    PhilipineTime,
    PhoenixIslandTime,
    PohnpeiStandardTime,
    ReunionTime,
    RotheraResearchStationTime,
    SaintPierreAndMiquelonDaylightTime,
    SaintPierreAndMiquelonStandardTime,
    SakhalinIslandTime,
    SamaraTime,
    SamoaDaylightTime,
    SamoaStandardTime,
    SeychellesTime,
    ShowaStationTime,
    SingaporeTime,
    SolomonIslandsTime,
    SouthAfricanStandardTime,
    SouthGeorgiaAndTheSouthSandwichIslandsTime,
    SrednekolymskTime,
    SriLankaStandardTime,
    SurinameTime,
    TahitiTime,
    TaiwanStandardTime,
    TajikistanTime,
    ThailandStandardTime,
    TimorLesteTime,
    TokelauTime,
    TongaTime,
    TurkeyTime,
    TurkmenistanTime,
    TuvaluTime,
    UlaanbaatarStandardTime,
    UlaanbaatarSummerTime,
    UruguayStandardTime,
    UruguaySummerTime,
    UzbekistanTime,
    VanuatuTime,
    VenezuelanStandardTime,
    VladivostokTime,
    VolgogradTime,
    VostokStationTime,
    WakeIslandTime,
    WestAfricaSummerTime,
    WestAfricaTime,
    WesternEuropeanSummerTime,
    WesternEuropeanTime,
    WesternIndonesianTime,
    WesternStandardTime,
    WestGreenlandSummerTime,
    WestGreenlandTime,
    YakutskTime,
    YekaterinburgTime,
}

// Display implementation

impl std::fmt::Display for TimeZone {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        let tmp_self_bind = format!("{:?}", self);
        let tmp_self = tmp_self_bind.replace("\"", "");
        let tmp_self = tmp_self.replace("TimeZone::", "");
        // its ascii!
        let mut tmp = tmp_self
            .chars()
            .map(|c| {
                if c.is_uppercase() {
                    " ".to_string() + &c.to_string()
                } else {
                    c.to_string()
                }
            })
            .collect::<String>();
        tmp = tmp.trim().to_string();
        // hacky but hey
        if tmp == "Utc" {
            tmp = "Coordinated Universal Time".to_string();
        }
        write!(f, "{}", tmp)
    }
}

impl From<String> for TimeZone {
    fn from(s: String) -> TimeZone {
        for tz in TimeZone::get_all() {
            if format!("{}", tz) == s {
                return tz;
            }
        }
        // Fallback
        TimeZone::CoordinatedUniversalTime
    }
}

impl TimeZone {
    /// Returns all time zones
    /// Convenient for testing or showing all time zones
    pub fn get_all() -> Vec<TimeZone> {
        vec![
            TimeZone::AcreTime,
            TimeZone::AfghanistanTime,
            TimeZone::AlaskanDaylightTime,
            TimeZone::AlaskanStandardTime,
            TimeZone::AlmaAtaTime,
            TimeZone::AmazonSummerTime,
            TimeZone::AmazonTime,
            TimeZone::AnadyrTime,
            TimeZone::AqtobeTime,
            TimeZone::ArabiaStandardTime,
            TimeZone::ArgentinaTime,
            TimeZone::ArmeniaTime,
            TimeZone::AtlanticDaylightTime,
            TimeZone::AtlanticStandardTime,
            TimeZone::AustralianCentralDaylightSavingTime,
            TimeZone::AustralianCentralStandardTime,
            TimeZone::AustralianEasternDaylightSavingTime,
            TimeZone::AustralianEasternStandardTime,
            TimeZone::AustralianWesternStandardTime,
            TimeZone::AzerbaijanTime,
            TimeZone::AzoresStandardTime,
            TimeZone::AzoresSummerTime,
            TimeZone::BakerIslandTime,
            TimeZone::BangaladeshStandardTime,
            TimeZone::BhutanTime,
            TimeZone::BoliviaTime,
            TimeZone::BougainvilleStandardTime,
            TimeZone::BrasiliaSummerTime,
            TimeZone::BrasiliaTime,
            TimeZone::BritishIndianOceanTime,
            TimeZone::BritishSummerTime,
            TimeZone::BruneiTime,
            TimeZone::CapeVerdeTime,
            TimeZone::CentralAfricaTime,
            TimeZone::CentralDaylightTime,
            TimeZone::CentralEuropeanSummerTime,
            TimeZone::CentralEuropeanTime,
            TimeZone::CentralIndonesianTime,
            TimeZone::CentralStandardTime,
            TimeZone::ChamorroStandardTime,
            TimeZone::ChathamDaylightTime,
            TimeZone::ChathamStandardTime,
            TimeZone::ChileStandardTime,
            TimeZone::ChileSummerTime,
            TimeZone::ChinaStandardTime,
            TimeZone::ChoibalsanStandardTime,
            TimeZone::ChoibalsanSummerTime,
            TimeZone::ChristmasIslandTime,
            TimeZone::ChuukTime,
            TimeZone::ClippertonIslandStandardTime,
            TimeZone::CocosIslandsTime,
            TimeZone::ColombiaSummerTime,
            TimeZone::ColombiaTime,
            TimeZone::CookIslandTime,
            TimeZone::CoordinatedUniversalTime,
            TimeZone::CubaDaylightTime,
            TimeZone::CubaStandardTime,
            TimeZone::DavisTime,
            TimeZone::DumontDUrvilleTime,
            TimeZone::EastAfricaTime,
            TimeZone::EasterIslandStandardTime,
            TimeZone::EasterIslandSummerTime,
            TimeZone::EasternCaribbeanTime,
            TimeZone::EasternDaylightTime,
            TimeZone::EasternEuropeanSummerTime,
            TimeZone::EasternEuropeanTime,
            TimeZone::EasternGreenlandSummerTime,
            TimeZone::EasternGreenlandTime,
            TimeZone::EasternIndonesianTime,
            TimeZone::EasternStandardTime,
            TimeZone::EcuadorTime,
            TimeZone::FalklandIslandsSummerTime,
            TimeZone::FalklandIslandsTime,
            TimeZone::FernandoDeNoronhaTime,
            TimeZone::FijiTime,
            TimeZone::FrenchGuianaTime,
            TimeZone::FrenchSouthernAndAntarcticTime,
            TimeZone::FurtherEasternEuropeanTime,
            TimeZone::GalapagosTime,
            TimeZone::GambierIslandsTime,
            TimeZone::GambierIslandTime,
            TimeZone::GeorgiaStandardTime,
            TimeZone::GilbertIslandTime,
            TimeZone::GreenwichMeanTime,
            TimeZone::GulfStandardTime,
            TimeZone::GuyanaTime,
            TimeZone::HawaiiAleutianDaylightTime,
            TimeZone::HawaiiAleutianStandardTime,
            TimeZone::HeardAndMcDonaldIslandsTime,
            TimeZone::HeureAvanceeDEuropeCentrale,
            TimeZone::HongKongTime,
            TimeZone::HovdTime,
            TimeZone::IndianOceanTime,
            TimeZone::IndianStandardTime,
            TimeZone::IndochinaTime,
            TimeZone::InternationalDateLineWestTime,
            TimeZone::IranDaylightTime,
            TimeZone::IranStandardTime,
            TimeZone::IrishStandardTime,
            TimeZone::IrkutskTime,
            TimeZone::IsraelDaylightTime,
            TimeZone::IsraelStandardTime,
            TimeZone::JapanStandardTime,
            TimeZone::KaliningradTime,
            TimeZone::KamchatkaTime,
            TimeZone::KoreaStandardTime,
            TimeZone::KosraeTime,
            TimeZone::KrasnoyarskTime,
            TimeZone::KyrgyzstanTime,
            TimeZone::LineIslandsTime,
            TimeZone::LordHoweStandardTime,
            TimeZone::LordHoweSummerTime,
            TimeZone::MacquarieIslandStationTime,
            TimeZone::MagadanTime,
            TimeZone::MalaysiaStandardTime,
            TimeZone::MalaysiaTime,
            TimeZone::MaldivesTime,
            TimeZone::MarquesasIslandsTime,
            TimeZone::MarshallIslandsTime,
            TimeZone::MauritiusTime,
            TimeZone::MawsonStationTime,
            TimeZone::MiddleEuropeanSummerTime,
            TimeZone::MiddleEuropeanTime,
            TimeZone::MoscowTime,
            TimeZone::MountainDaylightTime,
            TimeZone::MountainStandardTime,
            TimeZone::MyanmarStandardTime,
            TimeZone::NepalTime,
            TimeZone::NewCaledoniaTime,
            TimeZone::NewfoundlandDaylightTime,
            TimeZone::NewfoundlandStandardTime,
            TimeZone::NewfoundlandTime,
            TimeZone::NewZealandDaylightTime,
            TimeZone::NewZealandStandardTime,
            TimeZone::NiueTime,
            TimeZone::NorfolkIslandTime,
            TimeZone::NovosibirskTime,
            TimeZone::OmskTime,
            TimeZone::OralTime,
            TimeZone::PacificDaylightTime,
            TimeZone::PacificStandardTime,
            TimeZone::PakistanStandardTime,
            TimeZone::PalauTime,
            TimeZone::PapuaNewGuineaTime,
            TimeZone::ParaguaySummerTime,
            TimeZone::ParaguayTime,
            TimeZone::PeruTime,
            TimeZone::PhilipineStandardTime,
            TimeZone::PhilipineTime,
            TimeZone::PhoenixIslandTime,
            TimeZone::PohnpeiStandardTime,
            TimeZone::ReunionTime,
            TimeZone::RotheraResearchStationTime,
            TimeZone::SaintPierreAndMiquelonDaylightTime,
            TimeZone::SaintPierreAndMiquelonStandardTime,
            TimeZone::SakhalinIslandTime,
            TimeZone::SamaraTime,
            TimeZone::SamoaDaylightTime,
            TimeZone::SamoaStandardTime,
            TimeZone::SeychellesTime,
            TimeZone::ShowaStationTime,
            TimeZone::SingaporeTime,
            TimeZone::SolomonIslandsTime,
            TimeZone::SouthAfricanStandardTime,
            TimeZone::SouthGeorgiaAndTheSouthSandwichIslandsTime,
            TimeZone::SrednekolymskTime,
            TimeZone::SriLankaStandardTime,
            TimeZone::SurinameTime,
            TimeZone::TahitiTime,
            TimeZone::TaiwanStandardTime,
            TimeZone::TajikistanTime,
            TimeZone::ThailandStandardTime,
            TimeZone::TimorLesteTime,
            TimeZone::TokelauTime,
            TimeZone::TongaTime,
            TimeZone::TurkeyTime,
            TimeZone::TurkmenistanTime,
            TimeZone::TuvaluTime,
            TimeZone::UlaanbaatarStandardTime,
            TimeZone::UlaanbaatarSummerTime,
            TimeZone::UruguayStandardTime,
            TimeZone::UruguaySummerTime,
            TimeZone::UzbekistanTime,
            TimeZone::VanuatuTime,
            TimeZone::VenezuelanStandardTime,
            TimeZone::VladivostokTime,
            TimeZone::VolgogradTime,
            TimeZone::VostokStationTime,
            TimeZone::WakeIslandTime,
            TimeZone::WestAfricaSummerTime,
            TimeZone::WestAfricaTime,
            TimeZone::WesternEuropeanSummerTime,
            TimeZone::WesternEuropeanTime,
            TimeZone::WesternIndonesianTime,
            TimeZone::WesternStandardTime,
            TimeZone::WestGreenlandSummerTime,
            TimeZone::WestGreenlandTime,
            TimeZone::YakutskTime,
            TimeZone::YekaterinburgTime,
        ]
    }

    /// Returns the utc offset
    /// The format is in xx.yy
    /// where xx is hours and yy fractions of an hour
    pub fn get_utc_offset(&self) -> f64 {
        match self {
            TimeZone::AustralianCentralDaylightSavingTime => 10.5,
            TimeZone::AustralianCentralStandardTime => 9.5,
            TimeZone::AcreTime => -5.0,
            TimeZone::AtlanticDaylightTime => -3.0,
            TimeZone::AustralianEasternDaylightSavingTime => 11.0,
            TimeZone::AustralianEasternStandardTime => 10.0,
            TimeZone::AfghanistanTime => 4.5,
            TimeZone::AlaskanDaylightTime => -8.0,
            TimeZone::AlaskanStandardTime => -9.0,
            TimeZone::AlmaAtaTime => 6.0,
            TimeZone::AmazonSummerTime => -3.0,
            TimeZone::AmazonTime => -4.0,
            TimeZone::ArmeniaTime => 4.0,
            TimeZone::AnadyrTime => 12.0,
            TimeZone::AqtobeTime => 5.0,
            TimeZone::ArgentinaTime => -3.0,
            TimeZone::ArabiaStandardTime => 3.0,
            TimeZone::AtlanticStandardTime => -4.0,
            TimeZone::AustralianWesternStandardTime => 8.0,
            TimeZone::AzoresSummerTime => 0.0,
            TimeZone::AzoresStandardTime => -1.0,
            TimeZone::AzerbaijanTime => 4.0,
            TimeZone::BruneiTime => 8.0,
            TimeZone::BritishIndianOceanTime => 6.0,
            TimeZone::BakerIslandTime => -12.0,
            TimeZone::BoliviaTime => -4.0,
            TimeZone::BrasiliaSummerTime => -2.0,
            TimeZone::BrasiliaTime => -3.0,
            TimeZone::BangaladeshStandardTime => 6.0,
            TimeZone::BougainvilleStandardTime => 11.0,
            TimeZone::BritishSummerTime => 1.0,
            TimeZone::BhutanTime => 6.0,
            TimeZone::CentralAfricaTime => 2.0,
            TimeZone::CocosIslandsTime => 6.5,
            TimeZone::CentralDaylightTime => -5.0,
            TimeZone::CubaDaylightTime => -4.0,
            TimeZone::CentralEuropeanSummerTime => 2.0,
            TimeZone::CentralEuropeanTime => 1.0,
            TimeZone::ChathamDaylightTime => 13.75,
            TimeZone::ChathamStandardTime => 12.75,
            TimeZone::ChoibalsanStandardTime => 8.0,
            TimeZone::ChoibalsanSummerTime => 9.0,
            TimeZone::ChamorroStandardTime => 10.0,
            TimeZone::ChuukTime => 10.0,
            TimeZone::ClippertonIslandStandardTime => -8.0,
            TimeZone::CookIslandTime => -10.0,
            TimeZone::ChileSummerTime => -3.0,
            TimeZone::ChileStandardTime => -4.0,
            TimeZone::ColombiaSummerTime => -4.0,
            TimeZone::ColombiaTime => -5.0,
            TimeZone::CentralStandardTime => -6.0,
            TimeZone::ChinaStandardTime => 8.0,
            TimeZone::CubaStandardTime => -5.0,
            TimeZone::CapeVerdeTime => -1.0,
            TimeZone::ChristmasIslandTime => 7.0,
            TimeZone::DavisTime => 7.0,
            TimeZone::DumontDUrvilleTime => 10.0,
            TimeZone::EasterIslandSummerTime => -5.0,
            TimeZone::EasterIslandStandardTime => -6.0,
            TimeZone::EastAfricaTime => 3.0,
            TimeZone::EasternCaribbeanTime => -4.0,
            TimeZone::EcuadorTime => -5.0,
            TimeZone::EasternDaylightTime => -4.0,
            TimeZone::EasternEuropeanSummerTime => 3.0,
            TimeZone::EasternEuropeanTime => 2.0,
            TimeZone::EasternGreenlandSummerTime => 0.0,
            TimeZone::EasternGreenlandTime => -1.0,
            TimeZone::EasternStandardTime => -5.0,
            TimeZone::FurtherEasternEuropeanTime => 3.0,
            TimeZone::FijiTime => 12.0,
            TimeZone::FalklandIslandsSummerTime => -3.0,
            TimeZone::FalklandIslandsTime => -4.0,
            TimeZone::FernandoDeNoronhaTime => -2.0,
            TimeZone::GalapagosTime => -6.0,
            TimeZone::GambierIslandsTime => -9.0,
            TimeZone::GeorgiaStandardTime => 4.0,
            TimeZone::FrenchGuianaTime => -3.0,
            TimeZone::GilbertIslandTime => 12.0,
            TimeZone::GambierIslandTime => -9.0,
            TimeZone::GreenwichMeanTime => 0.0,
            TimeZone::SouthGeorgiaAndTheSouthSandwichIslandsTime => -2.0,
            TimeZone::GulfStandardTime => 4.0,
            TimeZone::GuyanaTime => -4.0,
            TimeZone::HawaiiAleutianDaylightTime => -9.0,
            TimeZone::HeureAvanceeDEuropeCentrale => 2.0,
            TimeZone::HawaiiAleutianStandardTime => -10.0,
            TimeZone::HongKongTime => 8.0,
            TimeZone::HeardAndMcDonaldIslandsTime => 5.0,
            TimeZone::HovdTime => 7.0,
            TimeZone::IndochinaTime => 7.0,
            TimeZone::InternationalDateLineWestTime => -12.0,
            TimeZone::IsraelDaylightTime => 3.0,
            TimeZone::IndianOceanTime => 6.0,
            TimeZone::IranDaylightTime => 4.5,
            TimeZone::IrkutskTime => 8.0,
            TimeZone::IranStandardTime => 3.5,
            TimeZone::IndianStandardTime => 5.5,
            TimeZone::IrishStandardTime => 1.0,
            TimeZone::IsraelStandardTime => 2.0,
            TimeZone::JapanStandardTime => 9.0,
            TimeZone::KaliningradTime => 2.0,
            TimeZone::KyrgyzstanTime => 6.0,
            TimeZone::KosraeTime => 11.0,
            TimeZone::KrasnoyarskTime => 7.0,
            TimeZone::KoreaStandardTime => 9.0,
            TimeZone::LordHoweStandardTime => 10.5,
            TimeZone::LordHoweSummerTime => 11.0,
            TimeZone::LineIslandsTime => 14.0,
            TimeZone::MagadanTime => 12.0,
            TimeZone::MarquesasIslandsTime => -9.5,
            TimeZone::MawsonStationTime => 5.0,
            TimeZone::MountainDaylightTime => -6.0,
            TimeZone::MiddleEuropeanTime => 1.0,
            TimeZone::MiddleEuropeanSummerTime => 2.0,
            TimeZone::MarshallIslandsTime => 12.0,
            TimeZone::MacquarieIslandStationTime => 11.0,
            TimeZone::MyanmarStandardTime => 6.5,
            TimeZone::MoscowTime => 3.0,
            TimeZone::MalaysiaStandardTime => 8.0,
            TimeZone::MountainStandardTime => -7.0,
            TimeZone::MauritiusTime => 4.0,
            TimeZone::MaldivesTime => 5.0,
            TimeZone::MalaysiaTime => 8.0,
            TimeZone::NewCaledoniaTime => 11.0,
            TimeZone::NewfoundlandDaylightTime => -2.5,
            TimeZone::NorfolkIslandTime => 11.0,
            TimeZone::NovosibirskTime => 7.0,
            TimeZone::NepalTime => 5.75,
            TimeZone::NewfoundlandStandardTime => -3.5,
            TimeZone::NewfoundlandTime => -3.5,
            TimeZone::NiueTime => -11.0,
            TimeZone::NewZealandDaylightTime => 13.0,
            TimeZone::NewZealandStandardTime => 12.0,
            TimeZone::OmskTime => 6.0,
            TimeZone::OralTime => 5.0,
            TimeZone::PacificDaylightTime => -7.0,
            TimeZone::PeruTime => -5.0,
            TimeZone::KamchatkaTime => 12.0,
            TimeZone::PapuaNewGuineaTime => 10.0,
            TimeZone::PhoenixIslandTime => 13.0,
            TimeZone::PhilipineTime => 8.0,
            TimeZone::PhilipineStandardTime => 8.0,
            TimeZone::PakistanStandardTime => 5.0,
            TimeZone::SaintPierreAndMiquelonDaylightTime => -2.0,
            TimeZone::SaintPierreAndMiquelonStandardTime => -3.0,
            TimeZone::PohnpeiStandardTime => 11.0,
            TimeZone::PacificStandardTime => -8.0,
            TimeZone::PalauTime => 9.0,
            TimeZone::ParaguaySummerTime => -3.0,
            TimeZone::ParaguayTime => -4.0,
            TimeZone::ReunionTime => 4.0,
            TimeZone::RotheraResearchStationTime => -3.0,
            TimeZone::SakhalinIslandTime => 11.0,
            TimeZone::SamaraTime => 4.0,
            TimeZone::SouthAfricanStandardTime => 2.0,
            TimeZone::SolomonIslandsTime => 11.0,
            TimeZone::SeychellesTime => 4.0,
            TimeZone::SamoaDaylightTime => -10.0,
            TimeZone::SingaporeTime => 8.0,
            TimeZone::SriLankaStandardTime => 5.5,
            TimeZone::SrednekolymskTime => 11.0,
            TimeZone::SurinameTime => -3.0,
            TimeZone::SamoaStandardTime => -11.0,
            TimeZone::ShowaStationTime => 3.0,
            TimeZone::TahitiTime => -10.0,
            TimeZone::ThailandStandardTime => 7.0,
            TimeZone::FrenchSouthernAndAntarcticTime => 5.0,
            TimeZone::TajikistanTime => 5.0,
            TimeZone::TokelauTime => 13.0,
            TimeZone::TimorLesteTime => 9.0,
            TimeZone::TurkmenistanTime => 5.0,
            TimeZone::TurkeyTime => 3.0,
            TimeZone::TongaTime => 13.0,
            TimeZone::TaiwanStandardTime => 8.0,
            TimeZone::TuvaluTime => 12.0,
            TimeZone::UlaanbaatarSummerTime => 9.0,
            TimeZone::UlaanbaatarStandardTime => 8.0,
            TimeZone::CoordinatedUniversalTime => 0.0,
            TimeZone::UruguaySummerTime => -2.0,
            TimeZone::UruguayStandardTime => -3.0,
            TimeZone::UzbekistanTime => 5.0,
            TimeZone::VenezuelanStandardTime => -4.0,
            TimeZone::VladivostokTime => 10.0,
            TimeZone::VolgogradTime => 3.0,
            TimeZone::VostokStationTime => 6.0,
            TimeZone::VanuatuTime => 11.0,
            TimeZone::WakeIslandTime => 12.0,
            TimeZone::WestAfricaSummerTime => 2.0,
            TimeZone::WestAfricaTime => 1.0,
            TimeZone::WesternEuropeanSummerTime => 1.0,
            TimeZone::WesternEuropeanTime => 0.0,
            TimeZone::WesternIndonesianTime => 7.0,
            TimeZone::EasternIndonesianTime => 9.0,
            TimeZone::CentralIndonesianTime => 8.0,
            TimeZone::WestGreenlandSummerTime => -2.0,
            TimeZone::WestGreenlandTime => -3.0,
            TimeZone::WesternStandardTime => 8.0,
            TimeZone::YakutskTime => 9.0,
            TimeZone::YekaterinburgTime => 5.0,
        }
    }
}

#[test]
fn get_all_timezones_and_convert_to_string_and_back() {
    for tz in TimeZone::get_all() {
        let tz_str = tz.to_string();
        let read_tz = TimeZone::from(tz_str);
        assert_eq!(tz, read_tz);
    }
}

#[test]
fn all_timezones() {
    use crate::Utc;

    let timezones = TimeZone::get_all();
    let tz_len = timezones.len();
    let mut test_vec: Vec<Utc> = Vec::new();
    for tz in timezones {
        let mut utc = Utc::now();
        utc.with_timezone(tz);
        test_vec.push(utc);
    }
    // really I am looking for crashes, I have no way of confirming the validity of the resulting
    // DateTime
    assert_eq!(tz_len, test_vec.len());
}

#[test]
fn print_timezones() {
    assert_eq!(
        "Irkutsk Time".to_string(),
        TimeZone::IrkutskTime.to_string()
    );
    assert_eq!(
        "Central European Summer Time".to_string(),
        TimeZone::CentralEuropeanSummerTime.to_string()
    );
    assert_eq!(
        "Chatham Daylight Time".to_string(),
        TimeZone::ChathamDaylightTime.to_string()
    );
    assert_eq!(
        "Chatham Standard Time".to_string(),
        TimeZone::ChathamStandardTime.to_string()
    );
    assert_eq!(
        "Central Africa Time".to_string(),
        TimeZone::CentralAfricaTime.to_string()
    );
    assert_eq!(
        "Greenwich Mean Time".to_string(),
        TimeZone::GreenwichMeanTime.to_string()
    );
    assert_eq!(
        "Venezuelan Standard Time".to_string(),
        TimeZone::VenezuelanStandardTime.to_string()
    );
    assert_eq!(
        "Coordinated Universal Time".to_string(),
        TimeZone::CoordinatedUniversalTime.to_string()
    );
}
